import { Restaurant } from "src/app/mock/restaurant";
import { Food } from "src/app/mock/food";
export const SORT={name:'Restaurant Name',averagePrice:'price',averageRating:'Rating'}
export const RESTAURANTS:Restaurant[] = [
{
    id: 5001,
    name: 'A2B',
    manager:null,

    fassaid: 23456789102345,
    gstNumber: '234567891023456',
    imageUrl:'https://content3.jdmagicbox.com/comp/chennai/h7/044pxx44.xx44.130405113636.n2h7/catalogue/a2b-veg-restaurant-pondy-bazaar-thyagaraya-nagar-chennai-pure-veg-restaurants-m87ak.jpg',
    cuisine:['South Indian'],
    address:{
        addressLine1:null,
        street:'Electronic City  Phase 1',
        city: 'Bengalore',
        pincode: 560100,
        state:'Karnataka'
    },
    timings:'9.00am-10.00pm',
    reviewList:[],
    orderList:[],
    notification:null,
    averageRating:4.5,
    averagePrice:150,
    type:['veg','Non-Veg']
},
{
    id:5002,
    name: 'Andhra',
    manager: null,
    fassaid: 23456789103456,
    gstNumber: '234567891034567',
    imageUrl:'https://content3.jdmagicbox.com/comp/chennai/74/044p9807974/catalogue/new-andhra-meals-hotel-ac-t-nagar-chennai-tandoori-restaurants-1nq3isf.jpg',
    cuisine:['South Indian'],
    address:{
        addressLine1:null,
        street:'Electronic City Phase 2',
        city: 'Bengalore',
        pincode: 560100,
        state:'Karnataka'
    },
    timings:'9.00am-10.00pm',
    reviewList:[],
    orderList:[],
    notification:null,
    averageRating:4.0,
    averagePrice:150,
    type:['veg','Non-Veg']
},
{
    id:5003,
    name:'Rajasthani Charbhuja',
    manager: null,
    fassaid: 23456789102345,
    gstNumber: '234567891023456',
    imageUrl:'https://fastly.4sqi.net/img/general/600x600/29303551_gzPfQOSS5XwQxdUdgpUZ040Q_70KZJNd0YZQko4gRFw.jpg',
    cuisine: ['North Indian'],
    address:{
        addressLine1:null,
        street:'Kormangala',
        city: 'Bengalore',
        pincode: 560100,
        state:'Karnataka'
    },
    timings:'9.00am-10.00pm',
    reviewList:[],
    orderList:[],
    notification:null,
    averageRating:4.5,
    averagePrice:150,
    type:['veg','Non-Veg']
},
{
    id:5004,
    name:'The Rasoiya Street',
    manager: null,
    fassaid: 233856945745877,
    gstNumber: '23547896584758',
    imageUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQ5lIhctm9KEcswJzgTWqJHVwltJhLZQRIvUcymJlk-lHeh4T5tQ',
    cuisine: ['North Indian'],
    address:{
        addressLine1:null,
        street:'BTM',
        city: 'Bengalore',
        pincode: 560100,
        state:'Karnataka'
    },
    timings:'9.00am-10.00pm',
    reviewList:[],
    orderList:[],
    notification:null,
    averageRating:3.5,
    averagePrice:150,
    type:['veg','Non-Veg']
},
{
    id:5005,
    name:'Sri Pillaiyar Bhavan',
    manager: null,
    fassaid: 23456328795642,
    gstNumber: '23568412576534',
    imageUrl:'https://content3.jdmagicbox.com/comp/bangalore/t9/080pxx80.xx80.170211182224.t8t9/catalogue/sri-pillaiyar-bhavan-electronic-city-bangalore-chettinad-restaurants-7jpk2.jpg',
    cuisine: ['South Indian'],
    address:{
        addressLine1:null,
        street:'BTM ',
        city: 'Bengalore',
        pincode: 560100,
        state:'Karnataka'
    },
    timings:'9.00am-10.00pm',
    reviewList:[],
    orderList:[],
    notification:null,
    averageRating:4.0,
    averagePrice:150,
    type:['veg','Non-Veg']
},
{
    id:5006,
    name:'Annapoorani',
    manager: null,
    fassaid: 2375845123689,
    gstNumber: '23487569125874',
    imageUrl:'http://annapooranicurryhouse.seojohor.com/wp-content/uploads/2016/04/Screen-Shot-2017-06-19-at-10.10.39-AM.png',
    cuisine: ['South Indian'],
    address:{
        addressLine1:null,
        street:'Silk Board',
        city: 'Bengalore',
        pincode: 560100,
        state:'Karnataka'
    },
    timings:'9.00am-10.00pm',
    reviewList:[],
    orderList:[],
    notification:null,
    averageRating:4.0,
    averagePrice:150,
    type:['veg','Non-Veg']
},
{
    id:5007,
    name:'Delhi Essense',
    manager: null,
    fassaid: 23412587963524,
    gstNumber: '23578469235415',
    imageUrl:'https://lh3.googleusercontent.com/pbYbWUSRt3gOe_aFQl13L0KN_ot6zavy6gpm_2hx7i7XOrN9zm5B_k52r1ckTa9tKdEXFHD9=w1080-h608-p-no-v0',
    cuisine: ['North Indian'],
    address:{
        addressLine1:null,
        street:'Silk Board',
        city: 'Bengalore',
        pincode: 560100,
        state:'Karnataka'
    },
    timings:'9.00am-10.00pm',
    reviewList:[],
    orderList:[],
    notification:null,
    averageRating:4.0,
    averagePrice:150,
    type:['veg','Non-Veg']
},
{
    id:5008,
    name:'Moriz',
    manager: null,
    fassaid: 234578695472365,
    gstNumber: '234512365897456',
    imageUrl:'https://cdn.restos.in/images/restaurants/5a9b9d081d41c837cb66444f/Y19Lan.jpg',
    cuisine: ['North Indian'],
    address:{
        addressLine1:null,
        street:'Kormangala',
        city: 'Bengalore',
        pincode: 560100,
        state:'Karnataka'
    },
    timings:'9.00am-10.00pm',
    reviewList:[],
    orderList:[],
    notification:null,
    averageRating:4.0,
    averagePrice:150,
    type:['veg','Non-Veg']
}
];
 


export const FOODS:Food[] = [
    {
        id:9001,
        name:'Idly',
        price:48.00,
        tax:2.00,
        restaurantId:5001,
        availability:true,
        imageUrl:'/',
        averageRating:4.5,
        description:"2 idly,sambar and chatiny",
        category:'Indian Breeds',
        cuisine:'South Indian' ,
        type:"veg"      

    },
    {
        id:9002,
        name:'Plain Dosa',
        price:48.00,
        tax:2.00,
        restaurantId:5001,
        availability:true,
        imageUrl:'/',
        averageRating:4.0,
        description:"1 Dosa,sambar and chatiny",
        category:'Indian Breeds',
        cuisine:'South Indian' ,
        type:"veg" 
    },
    {
        id:9003,
        name:'Onion Dosa',
        price:58.00,
        tax:2.00,
        restaurantId:5001,
        availability:true,
        imageUrl:'/',
        averageRating:4.5,
        description:"1 onion dosa,sambar and chatiny",
        category:'Indian Breeds',
        cuisine:'South Indian' ,
        type:"veg"

    },
    {
        id:9004,
        name:'Pongal',
        price:38.00,
        tax:2.00,
        restaurantId:5001,
        availability:true,
        imageUrl:'/',
        averageRating:4.5,
        description:"Pongal Rice,sambar and chatiny",
        category:'Rice',
        cuisine:'South Indian' ,
        type:"veg"  

    },
    {
        id:1001,
        name:'Poori',
        price:48.00,
        tax:2.00,
        restaurantId:5001,
        availability:true,
        imageUrl:'/',
        averageRating:4.0,
        description:"2 Poori,Channa Masala",
        category:'Indian Breeds',
        cuisine:'South Indian' ,
        type:"veg"
    },
    {
        id: 501,
        name: "Joallad Rotti",
        price: 50,
        tax: 0,
        restaurantId: 5004,
        category: "Biryani",
        availability: true,
        imageUrl: "assets\food\veg\veg\roti.jpeg",
        averageRating: 4.5,
        description: "1 leg piece,1 tikka piece with rice",
        cuisine: "SouthIndian",
        type:"Veg",
    },
    {
    id:502,
    name: "Holige",
    price: 50,
    tax: 0,
    restaurantId: 5004,
    category: "",
    availability: true,
    imageUrl: "assets\food\veg\holige.jpeg",
    averageRating: 5,
    description: "Bhadam holige with ghee",
    cuisine: "southIndian",
    type:"Veg",
    },
    {
    id:503,
    name: "Chapati curry",
    price: 50,
    tax: 0,
    restaurantId: 5004,
    category: "nonveg",
    availability: true,
    imageUrl: "assets\food\veg/chapati.jpeg",
    averageRating: 4.5,
    description: "Two chapati and twa types of curry",
    cuisine: "southIndian",
    type:"Veg"
    },
    {
    id:504,
    name: "Dhosa",
    price: 35,
    tax: 10,
    restaurantId: 5005,
    category: "veg",
    availability: true,
    imageUrl: "assets\food\veg\dhosa.jpeg",
    averageRating: 4.5,
    description: "Crispy dhosa with coconut chitney",
    cuisine: "southIndian",
    type:"Veg"
    },
    {
    id:505,
    name: "Idli vada",
    price: 40,
    tax: 10,
    restaurantId: 5004,
    category: "Breakfast",
    availability: true,
    imageUrl: "assets\food\veg\idli.jpeg",
    averageRating: 4.5,
    description: "1 bowl of noodles ",
    cuisine: "southIndian",
    type:"Veg"
    },
    {
     id:506,
    name: "Parota",
    price: 50,
    tax: 10,
    restaurantId: 5004,
    category: "parota",
    availability: true,
    imageUrl: "assets\food\veg\parota.jpeg",
    averageRating: 4.5,
    description: "Kerala  parota with curry",
    cuisine: "southIndian",
    type:"Veg"
    },
    {
     id:507,
    name: "Palav",
    price: 170,
    tax: 10,
    restaurantId: 5005,
    category: "Breakfast",
    availability: true,
    imageUrl: "assets\food\veg\palav.jpeg",
    averageRating: 4.5,
    description: "1 bowl of Palav",
    cuisine: "southIndian",
    type:"Veg"
    },
    {
        id:508,
        name: "FriedRice",
        price: 100,
        tax: 10,
        restaurantId: 5004,
        category: "meal",
        availability: true,
        imageUrl: "assets\food\veg\friedrice.jpeg",
        averageRating: 4.5,
        description: "1 plate of rice with saas ",
        cuisine: "chinese",
        type:"Veg"
        },
        {
         id:509,
        name: "Mirchi",
        price: 150,
        tax: 10,
        restaurantId: 5005,
        category: "snacks",
        availability: true,
        imageUrl: "assets\food\veg\mirchi.jpeg",
        averageRating: 4.5,
        description: " ",
        cuisine: "SouthIndian",
        type:"Veg"
        },
        {
            id:510,
        name: "Uddin vada",
        price: 50,
        tax: 10,
        restaurantId: 5005,
        category: "meal",
        availability: true,
        imageUrl: "",
        averageRating: 4.5,
        description: "2 vada with chtney",
        cuisine: "SouthIndian",
        type:"Veg"
        },
        {
            id:9001,
            name:'Idly',
            price:48.00,
            tax:2.00,
            restaurantId:5006,
            availability:true,
            imageUrl:'/',
            averageRating:4.5,
            description:"2 idly,sambar and chatiny",
            category:'Indian Breeds',
            cuisine:'South Indian' ,
            type:"veg"      
    
        },
        {
            id:9002,
            name:'Plain Dosa',
            price:48.00,
            tax:2.00,
            restaurantId:5006,
            availability:true,
            imageUrl:'/',
            averageRating:4.0,
            description:"1 Dosa,sambar and chatiny",
            category:'Indian Breeds',
            cuisine:'South Indian' ,
            type:"veg" 
        },
        {
            id:9003,
            name:'Onion Dosa',
            price:58.00,
            tax:2.00,
            restaurantId:5006,
            availability:true,
            imageUrl:'/',
            averageRating:4.5,
            description:"1 onion dosa,sambar and chatiny",
            category:'Indian Breeds',
            cuisine:'South Indian' ,
            type:"veg"
    
        },
        {
            id:9004,
            name:'Pongal',
            price:38.00,
            tax:2.00,
            restaurantId:5006,
            availability:true,
            imageUrl:'/',
            averageRating:4.5,
            description:"Pongal Rice,sambar and chatiny",
            category:'Rice',
            cuisine:'South Indian' ,
            type:"veg"  
    
        },
        {
            id:1001,
            name:'Poori',
            price:48.00,
            tax:2.00,
            restaurantId:5006,
            availability:true,
            imageUrl:'/',
            averageRating:4.0,
            description:"2 Poori,Channa Masala",
            category:'Indian Breeds',
            cuisine:'South Indian' ,
            type:"veg"
        },
]